### ISSUE TITLE
GSAP for AdWords without GWD

### ISSUE THREAD

**Issue by 13ogrammer** [joemidi/GSAP_AdWords_300x250#1]
Hey Joey,
Thanks for the great GSAP templates. Really appreciate it for sharing.
I was wondering if you have been able to use GSAP for HTML5 banners in AdWords without using GWD, hand-coded.

Thanks!

David

**Comment by joemidi** [comment]
Hey David,

I've never had my own AdWords account so I've been unable to test these templates. The GSAP forums might be better at shining a little light on the matter, but for the most part, all the threads seem to say AdWords is really harsh compared to all the others.
But you might ask there and find people with better answers than me!

Cheers, 
Joey

**Comment by joemidi** [comment]
@iamcrazydavid I just read a post on the GSAP forums http://greensock.com/forums/topic/12572-does-gsap-developers-has-any-plans-to-integrate-with-google-adwords/

The last points to this Google support page: https://support.google.com/adwordspolicy/answer/176108

> All code and assets must be referenced using a relative path to resources included in the .ZIP file. No external references are allowed except references to:
> Google Fonts
> Google-hosted jQuery
> **Google-hosted Greensock**
> Google-hosted CreateJS

Which is great news, you should be able to hand-code a GSAP banner using Google's hosted files.
https://support.google.com/richmedia/answer/6307288
